"""Wire field names for AnswerContract.

Generated by generate_answer_contract.py. Do not edit.
"""

from __future__ import annotations

ANSWER_CONTRACT_FIELDS: tuple[str, ...] = (
    'id',
    'takeaway',
    'narrative',
    'content',
    'figures',
    'charts',
    'sources',
    'document_snippets',
    'caveats',
    'derivation',
    'sql',
    'trace',
)
