import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
// @ts-expect-error -- a build script, deliberately outside the tsconfig projects.
import { envNames, renderDeployAppYaml } from './deploy-app-yaml.mjs';

const repoRoot = path.resolve(__dirname, '..');
const authored = readFileSync(path.join(repoRoot, 'app.yaml'), 'utf8');
const bundleYaml = readFileSync(path.join(repoRoot, '..', 'databricks.yml'), 'utf8');
const bundler = readFileSync(path.join(repoRoot, 'scripts', 'bundle-server.mjs'), 'utf8');

const DEPLOY_OVERRIDES = {
  banner: '# Generated by scripts/bundle-server.mjs from app.yaml. Edit that file, not this one.',
  command: "['node', 'server.mjs']",
  env: [{ name: 'NODE_ENV', value: 'production' }],
};

const GIT_DEPLOY_SCOPES = [
  'serving.serving-endpoints',
  'model-serving',
  'sql',
  'dashboards.genie',
  'catalog.catalogs:read',
  'catalog.schemas:read',
  'catalog.tables:read',
  'workspace.workspace:read',
  'postgres',
];

function declaredScopes(yaml: string): string[] {
  const value = /- name: PLAYER_INSIGHTS_USER_API_SCOPES\n\s+value: '?([^'\n]*)'?/.exec(yaml)?.[1] ?? '';
  return value.split(',').filter(Boolean);
}

describe('ADAPT deploy app.yaml generation', () => {
  it('carries every authored variable into the deploy target', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    for (const name of envNames(authored)) expect(generated).toContain(`name: ${name}`);
  });

  it('keeps resource-backed variables attached to ADAPT resources', () => {
    const generated = renderDeployAppYaml(authored, DEPLOY_OVERRIDES);
    expect(generated).toContain('valueFrom: postgres');
    expect(generated).toContain('valueFrom: serving-endpoint');
    expect(generated).toContain('valueFrom: sql-warehouse');
  });

  it('ships the exact Git-deploy OAuth fallback without retired search scopes', () => {
    expect(declaredScopes(renderDeployAppYaml(authored, DEPLOY_OVERRIDES))).toEqual(GIT_DEPLOY_SCOPES);
  });

  it('does not reintroduce retired retrieval or second-Genie settings', () => {
    const sources = `${authored}\n${bundleYaml}\n${bundler}`;
    const retiredSettings = new RegExp(
      [
        'PLAYER_INSIGHTS_DICT' + 'IONARY_GENIE',
        'PLAYER_INSIGHTS_SEMANTIC_' + '(?:INDEX|ENDPOINT)',
        'genie_dict' + 'ionary_space_id',
      ].join('|')
    );
    expect(sources).not.toMatch(retiredSettings);
  });

  it('bakes the app-owned catalog and customer group overrides', () => {
    expect(bundler).toContain("name: 'PLAYER_INSIGHTS_APP_CATALOG'");
    expect(bundler).toContain("name: 'ADAPT_ADMIN_GROUP'");
    expect(bundler).toContain("name: 'ADAPT_USER_GROUP'");
  });

  it('replaces overrides in place and keeps the generated command self-contained', () => {
    const generated = renderDeployAppYaml(authored, {
      ...DEPLOY_OVERRIDES,
      env: [...DEPLOY_OVERRIDES.env, { name: 'PLAYER_INSIGHTS_BUILD_SHA', value: "'abc123'" }],
    });
    expect(generated).toContain("command: ['node', 'server.mjs']");
    expect(generated).not.toContain("['npm', 'run', 'start']");
    expect(generated).toContain("name: PLAYER_INSIGHTS_BUILD_SHA\n    value: 'abc123'");
    expect(generated.match(/name: PLAYER_INSIGHTS_BUILD_SHA/g)).toHaveLength(1);
  });

  it('fails closed on malformed environment input', () => {
    expect(() => renderDeployAppYaml('env:\n  - valueFrom: postgres\n', {})).toThrow(/without a name/);
    expect(() => renderDeployAppYaml('env: []\n', { env: [{ name: 'A', value: 'b' }] })).toThrow(/inline env/);
  });
});
